### ISSUE TITLE
undefined reference to `softSerialBegin(long)'

### ISSUE THREAD

**Issue by DaveScream** [shimniok/ATtinySoftSerial#1]
I get error

cctm23Cg.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup+0x4a): undefined reference to `softSerialBegin(long)'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\digispark-tiny\firmware.elf] Error 1

**Comment by DaveScream** [comment]
If im tryint to include SoftwareSerial.c I get error

In file included from src\main.cpp:14:0:
include/SoftwareSerial.h:63:17: warning: redeclaration of C++ built-in type 'bool' [-fpermissive]
 typedef uint8_t bool;
                 ^
In file included from src\main.cpp:15:0:
include/SoftwareSerial.c: In function 'void softSerialBegin(long int)':
include/SoftwareSerial.c:223:25: error: 'table' was not declared in this scope
  for (i = 0; i < sizeof(table) / sizeof(table[0]); ++i) {
                         ^
include/SoftwareSerial.c:231:4: error: 'GIMSK' was not declared in this scope
    GIMSK |= (1<<PCIE);
    ^
include/SoftwareSerial.c:231:17: error: 'PCIE' was not declared in this scope
    GIMSK |= (1<<PCIE);
                 ^
include/SoftwareSerial.c:232:4: error: 'PCMSK' was not declared in this scope
    PCMSK |= (1<<RXPIN);
    ^
include/SoftwareSerial.c: In function 'void softSerialEnd()':
include/SoftwareSerial.c:244:2: error: 'PCMSK' was not declared in this scope
  PCMSK = 0;
  ^
include/SoftwareSerial.c: In function 'size_t softSerialWrite(uint8_t)':
include/SoftwareSerial.c:280:25: error: 'XMIT_START_ADJUSTMENT' was not declared in this scope
  tunedDelay(_tx_delay + XMIT_START_ADJUSTMENT);
                         ^
*** [.pio\build\digispark-tiny\src\main.o] Error 1

**Comment by shimniok** [comment]
What toolchain and version are you using for compile?

Are you actually including the .c file or linking it?

**Comment by shimniok** [comment]
> I get error
> 
> cctm23Cg.ltrans0.ltrans.o: In function `main': <artificial>:(.text.startup+0x4a): undefined reference to `softSerialBegin(long)'
> collect2.exe: error: ld returned 1 exit status
> *** [.pio\build\digispark-tiny\firmware.elf] Error 1

This is almost certainly because you didn't link the compiled object (.o) file for the TinySoftSerial.cpp with the object files in your project.

**Comment by shimniok** [comment]
No further response. Closing.
